<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Home</title>

	<!--BOOTSTRAP-->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	 <link rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }
            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 50px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
</head>
<body>
	<div class="row">
		<h1>TODO LIST</h1>
	  <h2>Login</h2>
		<div class="col-md-4 col-md-offset-4">
			<form method="post" action="auth">
				<div clas="form-group">
					<label for="user">Usuario</label>
					<input type="text" name="user" id="user" class="form-control"/>
				</div>
				<div clas="form-group">
					<label for="password">Contraseña</label>
					<input type="password" name="password" id="password" class="form-control"/><br>
				</div>
				<div class="col-md-2 col-md-offset-3">
					<input type="submit" value="Enviar" class="btn btn-primary">
				</div>
				<div class="col-md-2 col-md-offset-1">
					<a href="new" class="btn btn-info">Nuevo usuario</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>
