<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Listado de Productos</title>

		<!--BOOTSTRAP-->
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional tdeme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-tdeme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<link rel='stylesheet' type='text/css'>
	        <style>
	            body {
	                margin: 50px 0 0 0;
	                padding: 0;
	                widtd: 100%;
	                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	                text-align: center;
	                color: #aaa;
	                font-size: 14px;
	            }
							.header{
								border-bottom: 5px;
							}
	        </style>
	</head>
	<body>
		<div class="row">
			<h2>Listado de Productos</h2>
			<div class="col-md-8 col-md-offset-2">
			<?php if(is_array($all)): ?>
				<table class="table-bordered">
					<tr>
						<td>Nombre</td>
						<td>Descripción</td>
						<td>unidades</td>
						<td>Precio (€)</td>
						<td colspan="2">Acciones</td>
					</tr>
	      <?php foreach($all as $product):?>
	          <tr>
	              <td><?php echo $product['nombre']; ?></td>
								<td><?php echo $product['descripcion']; ?></td>
								<td><?php echo $product['unidades']; ?></td>
								<td><?php echo $product['precio']; ?>	€</td>
								<td>
									<a href="/delete?id=<?php echo $product['id'];?>" class="btn btn-danger btn-sm">Eliminar</a>
									<a href="/to-update?id=<?php echo $product['id'];?>" class="btn btn-info btn-sm">Actualizar</a>
								</td>
	          </tr>
	      <?php endforeach; ?>
			</table>
		</div>
				<div class="col-md-10 col-md-offset-1" style="margin-top:10px">
					<div class="col-md-2 col-md-offset-3">
						<a href="/new_prod" class="btn btn-primary">Nuevo producto</a>
					</div>
					<div class="col-md-2 col-md-offset-1">
						<a href="/logout" class="btn btn-default">Volver a inicio</a>
					</div>
				</div>
	    <?php endif; ?>
		</div>
	</body>
	</html>
