<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Nuevo usuario</title>

	<!--BOOTSTRAP-->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	 <link rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }
        </style>
</head>
<body>
	<div class="row">
	  <h2>Nuevo usuario</h2>
		<div class="col-md-4 col-md-offset-4">
			<form method="post" action="register">
				<div class="form-group">
					<label for="user">Usuario</label>
					<input type="text" name="user" id="user" class="form-control"/>
				</div>
				<div class="form-group">
					<label for="password">Contraseña</label>
					<input type="text" name="password" id="password" class="form-control"/>
				</div>
				<div class="form-group">
					<label for="email">E-mail</label>
					<input type="text" name="email" id="email" class="form-control"/>
				</div>
				<div class="col-md-2 col-md-offset-3">
					<input type="submit" value="Registrar" class="btn btn-info">
				</div>
				<div class="col-md-2 col-md-offset-2">
					<a href="/" class="btn btn-default">Volver</a>
				</div>
			</form>

		</div>
	</div>
</body>
</html>
