<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Actualizar Producto</title>

	<!--BOOTSTRAP-->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	 <link rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }
        </style>
</head>
<body>
	<div class="row">
	  <h2>Actualizar datos del producto</h2>
		<div class="col-md-4 col-md-offset-4">
			<form method="post" action="update">
			  <?php foreach($all as $product):?>
		        <input type="hidden" name="id" id="id" value="<?php echo $product['id']; ?>"/>
				    <div clas="form-group">
							<label for="name">Nombre</label>
							<input type="text" name="name" id="name" value="<?php echo $product['nombre']; ?>" class="form-control"/>
						</div>
				    <div clas="form-group">
							<label for="description">Descripción</label>
							<input type="text" name="description" id="description" value="<?php echo $product['descripcion']; ?> " class="form-control"/>
						</div>
				    <div clas="form-group">
							<label for="units">Unidades</label>
							<input type="tex" name="units" id="units" value="<?php echo $product['unidades']; ?> " class="form-control"/>
						</div>
		        <div clas="form-group">
							<label for="price">Precio</label>
							<input type="text" name="price" id="price" value="<?php echo $product['precio']; ?> " class="form-control"/>
						</div>
		    <?php endforeach; ?>
				<br>
				<div class="col-md-2 col-md-offset-3">
					<input type="submit" value="Enviar" class="btn btn-primary">
				</div>
				<div class="col-md-2 col-md-offset-1">
					<a href="list" class="btn btn-default">Cancelar</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>
